# Generated by Django 4.2 on 2024-11-04 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0010_permission_no_siri_roles_no_siri'),
        ('hms_kt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='registered_by_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='admin_kt.userrole'),
        ),
    ]
