# Generated by Django 4.2 on 2024-11-04 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0010_permission_no_siri_roles_no_siri'),
        ('hms_kt', '0002_hotel_registered_by_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='admin_kt.hoteltype')),
            ],
        ),
    ]
