# Generated by Django 4.2 on 2024-11-04 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0010_permission_no_siri_roles_no_siri'),
        ('hms_kt', '0003_selecthotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecthotel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='selecthotel',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_hotels', to='hms_kt.hotel'),
        ),
        migrations.AddField(
            model_name='selecthotel',
            name='hotel_facilities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_hotels', to='admin_kt.hotelfacilities'),
        ),
        migrations.AlterField(
            model_name='selecthotel',
            name='hotel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_hotels', to='admin_kt.hoteltype'),
        ),
    ]
