# Generated by Django 4.2 on 2024-11-04 04:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_kt', '0004_selecthotel_description_selecthotel_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecthotel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
