# Generated by Django 4.2 on 2024-11-05 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0010_permission_no_siri_roles_no_siri'),
        ('hms_kt', '0005_alter_selecthotel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecthotel',
            name='hotel_facilities',
        ),
        migrations.CreateModel(
            name='SelectFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_facilities', to='admin_kt.hotelfacilities')),
                ('select_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_facilities', to='hms_kt.selecthotel')),
            ],
        ),
    ]
