# Generated by Django 4.2 on 2024-11-05 04:04

from django.db import migrations, models
import django.db.models.deletion
import hms_kt.models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_kt', '0006_remove_selecthotel_hotel_facilities_selectfacilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hms_kt.models.hotel_image_upload_to)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hms_kt.hotel')),
            ],
        ),
    ]
