# Generated by Django 4.2 on 2024-11-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_kt', '0008_hotel_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListHmsModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
