# Generated by Django 4.2 on 2024-10-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_kt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
