# Generated by Django 4.2 on 2024-10-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_kt', '0003_remove_profile_full_name_remove_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
