# Generated by Django 4.2 on 2024-10-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_kt', '0004_profile_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identity_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
