# Generated by Django 4.2 on 2025-04-17 03:31

from django.db import migrations, models
import user_kt.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_kt', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[user_kt.models.validate_username]),
        ),
    ]
