# Generated by Django 4.2 on 2024-12-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_aboutus_page_contactus_page_mainchoose_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_pic', models.ImageField(upload_to='articles/')),
                ('main_caption', models.TextField()),
                ('second_pic', models.ImageField(upload_to='articles/')),
                ('second_caption', models.TextField()),
                ('third_pic', models.ImageField(upload_to='articles/')),
                ('third_caption', models.TextField()),
                ('fourth_pic', models.ImageField(upload_to='articles/')),
                ('fourth_caption', models.TextField()),
            ],
        ),
    ]
