# Generated by Django 4.2 on 2024-12-01 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_mainimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/')),
                ('caption', models.TextField()),
                ('main_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='page.mainimage')),
            ],
        ),
    ]
