# Generated by Django 4.2 on 2024-12-30 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package_kt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='package_kt.system'),
        ),
        migrations.AlterField(
            model_name='subpackage',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_packages', to='package_kt.package'),
        ),
        migrations.DeleteModel(
            name='SystemPackage',
        ),
    ]
