# Generated by Django 4.2 on 2024-12-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package_kt', '0002_package_system_alter_subpackage_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpackage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='package_kt.subpackage'),
        ),
    ]
