# Generated by Django 4.2 on 2024-12-30 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package_kt', '0004_remove_subpackage_parent_subpackage_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpackage_2',
            name='subpackage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_packages_2', to='package_kt.subpackage'),
        ),
    ]
