# Generated by Django 4.2 on 2024-12-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_kt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteAnalytics',
        ),
    ]
