# Generated by Django 4.2 on 2024-10-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0004_hotelfacilities_hotelroom_hoteltype_roomfacilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
