# Generated by Django 4.2 on 2024-11-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0005_hotelstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomfacilities',
            name='icon_main',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
