# Generated by Django 4.2 on 2024-11-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0006_roomfacilities_icon_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
