# Generated by Django 4.2 on 2024-11-02 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0007_roombed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombed',
            old_name='name',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='roomview',
            old_name='name',
            new_name='type_name',
        ),
    ]
