# Generated by Django 4.2 on 2024-11-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0010_permission_no_siri_roles_no_siri'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
