# Generated by Django 4.2 on 2024-11-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0012_listmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='admin_kt.listmodule'),
        ),
    ]
