# Generated by Django 4.2 on 2024-12-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0014_websiteanalytics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteAnalytics',
        ),
    ]
