# Generated by Django 4.2 on 2025-01-07 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package_kt', '0005_alter_subpackage_2_subpackage'),
        ('admin_kt', '0016_rolepackage_delete_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepackage',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_packages', to='package_kt.system'),
        ),
    ]
