# Generated by Django 4.2 on 2025-01-07 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0017_rolepackage_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepackage',
            name='system',
        ),
    ]
