# Generated by Django 4.2 on 2025-04-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0024_status_allowed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
