# Generated by Django 4.2 on 2025-04-09 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_kt', '0002_company'),
        ('admin_kt', '0025_status_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_roles', to='merchant_kt.company'),
        ),
    ]
