# Generated by Django 4.2 on 2025-04-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0026_userrole_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='can_receive_status_update',
            field=models.BooleanField(default=False),
        ),
    ]
