# Generated by Django 4.2 on 2025-04-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_kt', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
