# Generated by Django 4.2 on 2025-01-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0002_package_duration_package_end_date_package_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='pax',
        ),
        migrations.AddField(
            model_name='package',
            name='max_pax',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='min_pax',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
