# Generated by Django 4.2 on 2025-01-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0003_remove_package_pax_package_max_pax_package_min_pax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AddField(
            model_name='package',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
