# Generated by Django 4.2 on 2025-01-11 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0004_remove_location_name_package_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='type',
        ),
    ]
