# Generated by Django 4.2 on 2025-01-11 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0005_remove_package_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='pack_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pack_list_kt.status'),
        ),
    ]
