# Generated by Django 4.2 on 2025-01-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0006_status_package_pack_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='color',
        ),
    ]
