# Generated by Django 4.2 on 2025-01-21 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0009_package_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='packageitem',
            name='merchant_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pack_list_kt.merchantpackage'),
        ),
    ]
