# Generated by Django 4.2 on 2025-01-21 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0023_merchantlist_merchantlogin_merchantcategory'),
        ('pack_list_kt', '0010_merchantpackage_packageitem_merchant_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageMerchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('merchant_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('main_merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_merchants', to='admin_kt.mainmerchant')),
                ('merchant_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_merchants', to='pack_list_kt.merchantpackage')),
                ('merchant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_merchants', to='admin_kt.merchanttype')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_merchants', to='pack_list_kt.package')),
            ],
        ),
    ]
