# Generated by Django 4.2 on 2025-01-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0010_merchantpackage_packagemerchant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagemerchant',
            name='name',
        ),
    ]
