# Generated by Django 4.2 on 2025-01-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0011_packagemerchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagemerchant',
            name='main_merchant',
        ),
    ]
