# Generated by Django 4.2 on 2025-01-26 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0011_remove_packagemerchant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageitem',
            name='commission_percent',
        ),
        migrations.RemoveField(
            model_name='packageitem',
            name='merchant_price',
        ),
        migrations.RemoveField(
            model_name='packageitem',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='packageitem',
            name='adult_agent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='adult_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='adult_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='adult_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='children_agent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='children_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='children_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='children_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='product_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack_item', to='pack_list_kt.productdetails'),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='merchant_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack_item', to='pack_list_kt.packagemerchant'),
        ),
    ]
