# Generated by Django 4.2 on 2025-01-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0012_remove_packageitem_commission_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageitem',
            name='name',
        ),
        migrations.AddField(
            model_name='packageitem',
            name='adult_commission_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='children_commission_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='grand_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='total_adult_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='total_children_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='adult_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='children_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
