# Generated by Django 4.2 on 2025-01-21 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0012_remove_packagemerchant_main_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageitem',
            name='package',
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='merchant_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack_price', to='pack_list_kt.packagemerchant'),
        ),
    ]
