# Generated by Django 4.2 on 2025-01-23 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0014_merchantpackage_city_merchantpackage_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpackage',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_packages', to='pack_list_kt.location'),
        ),
    ]
