# Generated by Django 4.2 on 2025-01-30 07:17

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0014_productitemtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitemtotal',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='productitemtotal',
            name='package_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_totals', to='pack_list_kt.packageitem'),
        ),
        migrations.AlterField(
            model_name='productitemtotal',
            name='total_selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
