# Generated by Django 4.2 on 2025-01-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0015_alter_merchantpackage_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
