# Generated by Django 4.2 on 2025-01-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0017_remove_productitemtotal_package_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitemtotal',
            name='package_item',
        ),
        migrations.AddField(
            model_name='productitemtotal',
            name='package_items',
            field=models.ManyToManyField(related_name='package_totals', to='pack_list_kt.packageitem'),
        ),
    ]
