# Generated by Django 4.2 on 2025-01-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0018_remove_productitemtotal_package_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitemtotal',
            name='package_items',
        ),
        migrations.CreateModel(
            name='PackageItemTotalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('package_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_totals', to='pack_list_kt.packageitem')),
                ('product_item_total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='pack_list_kt.productitemtotal')),
            ],
        ),
    ]
