# Generated by Django 4.2 on 2025-01-31 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0019_remove_productitemtotal_package_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitemtotal',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='productitemtotal',
            name='grand_total',
        ),
    ]
