# Generated by Django 4.2 on 2025-03-23 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0022_remove_packageitemtotallink_merchant_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitemtotal',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_totals', to='pack_list_kt.packagemerchant'),
        ),
    ]
