# Generated by Django 4.2 on 2025-03-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0023_productitemtotal_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitemtotal',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_total', to='pack_list_kt.packagemerchant'),
        ),
    ]
