# Generated by Django 4.2 on 2025-03-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0024_alter_productitemtotal_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitemtotallink',
            name='package_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_totals', to='pack_list_kt.packageitem'),
        ),
        migrations.AlterField(
            model_name='packageitemtotallink',
            name='product_item_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='pack_list_kt.productitemtotal'),
        ),
    ]
