# Generated by Django 4.2 on 2025-04-07 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0025_alter_packageitemtotallink_package_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitemtotallink',
            name='package_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_totals', to='pack_list_kt.packageitem'),
        ),
        migrations.AlterField(
            model_name='packageitemtotallink',
            name='product_item_total',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='pack_list_kt.productitemtotal'),
        ),
        migrations.AlterField(
            model_name='productitemtotal',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_totals', to='pack_list_kt.packagemerchant'),
        ),
    ]
