# Generated by Django 4.2 on 2025-04-09 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0025_status_color'),
        ('pack_list_kt', '0027_alter_packageitemtotallink_package_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='pack_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_kt.status'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
