# Generated by Django 4.2 on 2025-04-09 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0026_userrole_company'),
        ('pack_list_kt', '0028_alter_package_pack_status_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='pack_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_kt.status'),
        ),
    ]
