# Generated by Django 4.2 on 2025-04-09 03:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0026_userrole_company'),
        ('pack_list_kt', '0029_alter_package_pack_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='pack_list_kt.package')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_kt.status')),
                ('user_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_kt.userrole')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
