# Generated by Django 4.2 on 2025-04-10 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_kt', '0027_roles_can_receive_status_update'),
        ('pack_list_kt', '0030_packagelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagelog',
            name='user_role',
        ),
        migrations.AddField(
            model_name='packagelog',
            name='from_user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_packages', to='admin_kt.userrole'),
        ),
        migrations.AddField(
            model_name='packagelog',
            name='to_user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_packages', to='admin_kt.userrole'),
        ),
    ]
