# Generated by Django 4.2 on 2025-04-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0032_packcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOtherImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/others/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_images', to='pack_list_kt.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageMainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/main/')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='pack_list_kt.package')),
            ],
        ),
    ]
