# Generated by Django 4.2 on 2025-04-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0033_packageotherimage_packagemainimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageotherimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='packageotherimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
