# Generated by Django 4.2 on 2025-04-17 03:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack_list_kt', '0036_packageotherimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
